myproject/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("post/<int:id>/", views.PostDetailView.as_view(), name="details"),
]

myproject/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.book_list, name="list"),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path("book/<int:id>/", views.book_details, name="details"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("simplerouting.urls")),
    path('matematyka/', include('matematyka.urls')),
    path("blog/", include("blog.urls")),
    path("books/", include("books.urls")),
    path("news/", include("news.urls")),
    path("", include("modele.urls")),
]

myproject/books/models.py
from django.db import models

class Book(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    year = models.PositiveIntegerField()
    description = models.TextField()
    price = models.PositiveIntegerField()


    def __str__(self):
        return self.title

myproject/books/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from .services import book_service
from .models import Book
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, CreateView

# Create your views here.
def book_list(request):

    paginator = Paginator(book_service.get_books(), 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "books/list.html", {"page_obj": page_obj})


def book_details(request, id):
    book = book_service.get_book(id)

    return render(request, "books/details.html", {"book": book})

class BookCreateView(CreateView):
    model = Book
    fields = ["id", "title", "author", "year", "description", "price"]
    success_url = reverse_lazy("books:list")

myproject/books/templates/books/book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Utwórz książkę</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Dodaj</button>
    </form>
{% endblock content %}

myproject/books/templates/books/details.html
{% extends "base.html" %}

{% block title %}Szczegóły wybranej książki{% endblock %}

{% block content %}
<h1>{{ book.title }}</h1>
<p><strong>Autor:</strong> {{ book.author }}</p>
<p><strong>Rok wydania:</strong> {{ book.year }}</p>
<p><strong>Cena:</strong> {{ book.price }} zł</p>
<hr>
<p>{{ book.description }}</p>
{% endblock %}

myproject/books/templates/books/list.html
{% extends "base.html" %}

{% block title %}Lista książek{% endblock %}

{% block content %}
<div class="row">
    {% for book in page_obj %}

    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p><strong>Autor:</strong> {{ book.author }}</p>
                <p><strong>Rok:</strong> {{ book.year }}</p>
                <p><strong>Cena:</strong> {{ book.price }} zł</p>
                <p class="card-text">{{ book.snippet }}</p>
                <a href="{% url 'books:details' book.id %}" class="stretched-link"></a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}