myproject/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("post/<int:id>/", views.PostDetailView.as_view(), name="details"),
]

myproject/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.book_list, name="list"),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path("book/<int:id>/", views.book_details, name="details"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("simplerouting.urls")),
    path('matematyka/', include('matematyka.urls')),
    path("blog/", include("blog.urls")),
    path("books/", include("books.urls")),
    path("news/", include("news.urls")),
    path("", include("modele.urls")),
]

myproject/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news/', views.news_list, name='list'),
    path('news/<int:pk>/', views.news_details, name='details'),
    path("news/author/add/", views.author_add, name="author_add"),
]

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">


</head>
<body>

<div class="container">
    <header>

        <h1>>>>>>>>>>>>>>>>>>>>>>>ALX>>>>>>>>>>>>>>>>>>>>>></h1>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

            <div class="container-fluid">
                <ul class="nav">
                    <li class="nav-item"><a class="nav-link active" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:list' %}">Blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'books:list' %}">Books</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'news:list' %}">News</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button"
                           data-bs-toggle="dropdown">Dropdown</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Link</a></li>
                            <li><a class="dropdown-item" href="#">Another link</a></li>
                            <li><a class="dropdown-item" href="#">A third link</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="/matematyka/">Matematyka</a></li>
                    <li class="nav-item"><a class="nav-link" href="javascript:void(0)">About</a></li>

                    <li class="nav-item "><a class="nav-link" href="#">Logout</a></li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        {% include 'includes/user_info.html' %}
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% block content %}

    {% endblock %}

</div>


<footer style="margin-top: 40px; padding: 20px; border-top: 1px solid #ccc;">
    Redakcja to: {{ redakcja }}
    <p>
        Statystyki serwisu:
        Autorów: <strong>{{ ilosc_autorow }}</strong> |
        Newsów: <strong>{{ ilosc_newsow }}</strong> |

    </p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>