myproject/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("post/<int:id>/", views.PostDetailView.as_view(), name="details"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("simplerouting.urls")),
    path('matematyka/', include('matematyka.urls')),
    path("blog/", include("blog.urls")),
    path("books/", include("books.urls")),
    path("news/", include("news.urls")),
    path("", include("modele.urls")),
]

myproject/blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

    def length(self):
        return len(self.content)

    def get_snippet(self, max_len=100):
        if len(self.content) <= max_len:
            return self.content
        return self.content[:100] + "..."

myproject/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post
from .services import blog

import logging

logger = logging.getLogger(__name__)


class PostListView(ListView):
    model = Post
    template_name = "blog/list.html"
    paginate_by = 9

    def get_queryset(self):
        return Post.objects.order_by("-id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logger.info(
            f"Pobieram stronę: {self.request.GET.get('page')} "
            f"z {context['paginator'].num_pages}"
        )
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/details.html"
    pk_url_kwarg = "id"
    context_object_name = "post" # to chyba zbędne

myproject/blog/templates/blog/details.html
{% extends "base.html" %}

{% block title %}Szczegóły wybranego posta{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
{% endblock %}

myproject/blog/templates/blog/list.html
{% extends "base.html" %}

{% block title %}Lista postów{% endblock %}

{% block content %}
<div class="row">
    {% for post in page_obj %}

    <div class="col-md-4">
        <a href="{% url 'blog:details' post.id %}">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.snippet }}</p>
                </div>
            </div>
        </a>
    </div>

    {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}